### ISSUE TITLE
Mapa mental Actividad_1

### ISSUE THREAD

**Issue by MLR062998** [SistemasTecTlaxiaco/actividad-1-mapa-mental-MLR062998#1]
[Mapa mental activada_1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-MLR062998/files/10714010/Mapa.mental.activada_1.pdf)

**Comment by Gregorio012** [comment]
19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
